import React, { useState, useEffect } from "react";
import Button from "@mui/material/Button";
import Dialog from "@mui/material/Dialog";
import DialogActions from "@mui/material/DialogActions";
import DialogContent from "@mui/material/DialogContent";
import DialogTitle from "@mui/material/DialogTitle";
import { TextField, MenuItem, Grid } from "@mui/material";

// utils
import AutoGeneratedFieldGroup from "components/AutoGeneratedFieldGroup";

export default function DialogMenu(props) {
  const [open, setOpen] = useState(props.open);
  const [modifiedData, setModifiedData] = useState(props.data);

  const handleClose = (action) => {
    setOpen(false);
    if (action == "save") {
      if (props.onClose) props.onClose(modifiedData);
    } else if (props.onClose) props.onClose(null);
  };

  // open check
  useEffect(() => {
    setOpen(props.open);
  }, [props.open]);

  return (
    <Dialog
      open={open}
      onClose={handleClose}
      scroll={"paper"}
      aria-labelledby="scroll-dialog-title"
      aria-describedby="scroll-dialog-description"
    >
      <DialogTitle id="scroll-dialog-title">{props.title}</DialogTitle>
      <DialogContent dividers={true}>
        <AutoGeneratedFieldGroup
          data={props.data}
          onChange={(data) => {
            setModifiedData(data);
          }}
        />
      </DialogContent>
      <DialogActions>
        <Button onClick={() => handleClose("cancel")}>Cancel</Button>
        <Button onClick={() => handleClose("save")}>Save</Button>
      </DialogActions>
    </Dialog>
  );
}
